config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :articles do
    resources :comments, only: [:create]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  validates :title, :text, presence: true
  validates :title, length: { minimum: 6 }

  after_validation :format_title

  scope :latest, -> { order("created_at DESC").limit(5) }

  def format_title
    self.title = title.titleize
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :ensure_logged_in, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)

    # You can also do
    # @article = Article.new(article_params)
    # @article.user_id = current_user.id

    # PATH vs. URL
    # article_path => "/articles/3"
    # article_url => "http://localhost:3000/articles/3"

    if @article.save
      flash[:notice] = "This article was successfully created. YAY!"
      redirect_to article_path(@article)
    else
      flash.now[:alert] = "OMG SOMETHING BAD HAPPENED. BOO."
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = @article.comments.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    @article.update(article_params)
    redirect_to article_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :ensure_logged_in
  before_action :load_article

  def create
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to article_path(@article), notice: "Thank you for your comment."
    else
      flash.now[:alert] = "Your comment failed to be created."
      render 'articles/show'
    end
  end

  def edit
    # ....
  end

  def update
    # ....
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def load_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      # log in / create session
      session[:user_id] = user.id
      redirect_to root_url, notice: "Successfully logged in!"
    else
      flash.now[:alert] = "Please log in"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit!
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @latest_articles = Article.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, 'error') %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<p>
  <strong>Title: </strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text: </strong>
  <%= @article.text %>
</p>


<% @article.comments.each do |comment| %>
  <% if comment.id %>
    <p><%= comment.body %></p>
    <span>by <%= comment.user.first_name %>
  <% end %>
<% end %>

<%= form_for [@article, @comment] do |f| %>
  <%= f.label :body, "Add your comment" %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

<%= link_to 'Edit this article', edit_article_path(@article) %>

<%= link_to 'Back to articles', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.first_name %>. <%= link_to "Log out", session_path(current_user.id), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </div>

    <div class="notifications">
      <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert] %></p>
      <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>

<% @latest_articles.each do |article| %>
  <h1><a href="<%= article_path(article) %>"><%= article.title %></a></h1>
<% end %>